//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmdPal.VaultSearchExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmdPal.VaultSearchExtension.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 拷贝 的本地化字符串。
        /// </summary>
        internal static string action_copy {
            get {
                return ResourceManager.GetString("action_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拷贝内容 的本地化字符串。
        /// </summary>
        internal static string action_copy_content {
            get {
                return ResourceManager.GetString("action_copy_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拷贝路径 的本地化字符串。
        /// </summary>
        internal static string action_copy_path {
            get {
                return ResourceManager.GetString("action_copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拷贝到剪切板 的本地化字符串。
        /// </summary>
        internal static string action_copy_toast {
            get {
                return ResourceManager.GetString("action_copy_toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string action_open {
            get {
                return ResourceManager.GetString("action_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在资源管理器中打开 的本地化字符串。
        /// </summary>
        internal static string action_open_in_folder {
            get {
                return ResourceManager.GetString("action_open_in_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开方式 的本地化字符串。
        /// </summary>
        internal static string action_open_with {
            get {
                return ResourceManager.GetString("action_open_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string action_settings {
            get {
                return ResourceManager.GetString("action_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 Vault 中的文件或内容 的本地化字符串。
        /// </summary>
        internal static string app_display_subtitle {
            get {
                return ResourceManager.GetString("app_display_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vault 搜索 的本地化字符串。
        /// </summary>
        internal static string app_display_title {
            get {
                return ResourceManager.GetString("app_display_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &gt;  的本地化字符串。
        /// </summary>
        internal static string constants_command_start {
            get {
                return ResourceManager.GetString("constants_command_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后编辑时间 的本地化字符串。
        /// </summary>
        internal static string detail_file_last_modified {
            get {
                return ResourceManager.GetString("detail_file_last_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        internal static string detail_file_path {
            get {
                return ResourceManager.GetString("detail_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        internal static string detail_file_size {
            get {
                return ResourceManager.GetString("detail_file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        internal static string detail_file_tag {
            get {
                return ResourceManager.GetString("detail_file_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 摘要 的本地化字符串。
        /// </summary>
        internal static string detail_title {
            get {
                return ResourceManager.GetString("detail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按 [ Enter ↵ ] 设置 Vault 位置 的本地化字符串。
        /// </summary>
        internal static string item_error_vault_path_subtitle {
            get {
                return ResourceManager.GetString("item_error_vault_path_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vault 路径设置错误 的本地化字符串。
        /// </summary>
        internal static string item_error_vault_path_title {
            get {
                return ResourceManager.GetString("item_error_vault_path_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按 [ Enter ↵ ] 设置 Vault 位置 的本地化字符串。
        /// </summary>
        internal static string item_no_vault_path_subtitle {
            get {
                return ResourceManager.GetString("item_no_vault_path_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vault 路径未设置 的本地化字符串。
        /// </summary>
        internal static string item_no_vault_path_title {
            get {
                return ResourceManager.GetString("item_no_vault_path_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按 [ Enter ⏎ ] 重建索引 的本地化字符串。
        /// </summary>
        internal static string item_reload_index_subtitle {
            get {
                return ResourceManager.GetString("item_reload_index_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重建索引 的本地化字符串。
        /// </summary>
        internal static string item_reload_index_title {
            get {
                return ResourceManager.GetString("item_reload_index_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始重建索引，大概需要几秒 的本地化字符串。
        /// </summary>
        internal static string item_reload_index_toast {
            get {
                return ResourceManager.GetString("item_reload_index_toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按 [ Enter ⏎ ] 去设置 的本地化字符串。
        /// </summary>
        internal static string item_settings_subtitle {
            get {
                return ResourceManager.GetString("item_settings_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string item_settings_title {
            get {
                return ResourceManager.GetString("item_settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vault.search.page.dynamic 的本地化字符串。
        /// </summary>
        internal static string page_dynamic_id {
            get {
                return ResourceManager.GetString("page_dynamic_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 Vault 的本地化字符串。
        /// </summary>
        internal static string page_dynamic_name {
            get {
                return ResourceManager.GetString("page_dynamic_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按 [ &gt; ] + [ Space ␣ ] 显示操作列表 的本地化字符串。
        /// </summary>
        internal static string page_dynamic_placeholder {
            get {
                return ResourceManager.GetString("page_dynamic_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 Search 的本地化字符串。
        /// </summary>
        internal static string page_dynamic_title {
            get {
                return ResourceManager.GetString("page_dynamic_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vault.search.page.fallback 的本地化字符串。
        /// </summary>
        internal static string page_fallback_id {
            get {
                return ResourceManager.GetString("page_fallback_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 Vaults  的本地化字符串。
        /// </summary>
        internal static string page_fallback_title {
            get {
                return ResourceManager.GetString("page_fallback_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vault.search.page.help 的本地化字符串。
        /// </summary>
        internal static string page_help_id {
            get {
                return ResourceManager.GetString("page_help_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string page_help_name {
            get {
                return ResourceManager.GetString("page_help_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string page_help_title {
            get {
                return ResourceManager.GetString("page_help_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vault.search.page.markdown 的本地化字符串。
        /// </summary>
        internal static string page_markdown_id {
            get {
                return ResourceManager.GetString("page_markdown_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string page_markdown_subtitle {
            get {
                return ResourceManager.GetString("page_markdown_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string page_markdown_title {
            get {
                return ResourceManager.GetString("page_markdown_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配文件内容，占用更多内存 的本地化字符串。
        /// </summary>
        internal static string settings_index_content_description {
            get {
                return ResourceManager.GetString("settings_index_content_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容匹配 的本地化字符串。
        /// </summary>
        internal static string settings_index_content_title {
            get {
                return ResourceManager.GetString("settings_index_content_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Markdown 文件使用 frontmatter 中的 tags, Txt 文件使用内容中以 # 开始的词组 的本地化字符串。
        /// </summary>
        internal static string settings_index_tags_description {
            get {
                return ResourceManager.GetString("settings_index_tags_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签匹配 的本地化字符串。
        /// </summary>
        internal static string settings_index_tags_title {
            get {
                return ResourceManager.GetString("settings_index_tags_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动加载 Obsidian 的 Vaults 的本地化字符串。
        /// </summary>
        internal static string settings_obsidian_vault_description {
            get {
                return ResourceManager.GetString("settings_obsidian_vault_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Obsidian Vault 的本地化字符串。
        /// </summary>
        internal static string settings_obsidian_vault_title {
            get {
                return ResourceManager.GetString("settings_obsidian_vault_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动显示详情面板 的本地化字符串。
        /// </summary>
        internal static string settings_show_details_description {
            get {
                return ResourceManager.GetString("settings_show_details_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详情 的本地化字符串。
        /// </summary>
        internal static string settings_show_details_title {
            get {
                return ResourceManager.GetString("settings_show_details_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vault 路径 - 多个用 [ ; ] 分隔 的本地化字符串。
        /// </summary>
        internal static string settings_vault_path_description {
            get {
                return ResourceManager.GetString("settings_vault_path_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vault 路径 的本地化字符串。
        /// </summary>
        internal static string settings_vault_path_title {
            get {
                return ResourceManager.GetString("settings_vault_path_title", resourceCulture);
            }
        }
    }
}
